/* Este archivo se tiene que llamar así para que lo coja la arquitectura */
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (1, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (2, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (3, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (4, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (5, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (6, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (7, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (8, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (9, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (10, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (11, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (12, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (13, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (14, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (15, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (16, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (17, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (18, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (19, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (20, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (21, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (22, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (23, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (24, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (25, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (26, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (27, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (28, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (29, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (30, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (31, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (32, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (33, 'Julio', 'Sepulveda', 'julio240688@gmail.com', '2021-11-25', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (34, 'Rocío', 'García', 'rocio271086@gmail.com', '2021-12-25', '');

INSERT INTO productos (nombre, precio, create_at) VALUES ('Panasonic Pantalla LCD', 259990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Sony Camara digital DSC-W3208', 123490, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Apple Ipod Shuffle', 1499990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Sony Notebook Z110', 37990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Hewlett Packard Multifuncional F2280', 69990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Bianchi Bicicleta Aro 26', 69990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mica Comoda 5 Cajones', 299990, NOW());

INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES ('Factura equipos de oficina', null, 1, NOW());
INSERT INTO facturas_items(cantidad, factura_id, producto_id) VALUES (1, 1, 1);
INSERT INTO facturas_items(cantidad, factura_id, producto_id) VALUES (2, 1, 4);
INSERT INTO facturas_items(cantidad, factura_id, producto_id) VALUES (1, 1, 5);
INSERT INTO facturas_items(cantidad, factura_id, producto_id) VALUES (1, 1, 7);

INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES ('Factura Bicicleta', 'Alguna nota importante!', 1, NOW());
INSERT INTO facturas_items(cantidad, factura_id, producto_id) VALUES (3, 2, 6);
